### ISSUE TITLE
Small issues / tweaks with Delta view

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting#339]
Created this issue to catch the small things that pop up on Delta view in staging. 

- [x] 1. Can we change the text when you click on a future time from "GSP-level delta values not yet available for future" to "Delta values not available for times in the future."
- [x] 2.   At 10.05 in the morning, if I look at the current time period (10.00), it shows the delta as the difference between the forecast and zero.  In the future, it is fine - so I think it's just that the current period needs to be treated like the future (or until there are PV_Live values in there).
- [x] 3. Can we remove the time label (I.e. 10.00) below the GSP line graph, as it overlaps with the buttons below.  I think it's OK to remove, but keep the vertical line, as the time box is visible for the national line chart above. 
- [x] 4. In the tooltip for the line graph and the map, can we limit the number of decimal places in the delta to 1 dp at most?  Atm it is mostly no dps, but for small numebrs it it 2 dp, which is a bit too much detail.
- [ ] 5. For the map tooltip, can we swap the order of the rows (I.e. human readable name on top), and delete the #n figure.  Noone uses the numbers I don't think.

**Comment by braddf** [comment]
Hey @dantravers - have checked off 4/5 of these and should be just deploying to `staging` imminently 🤞 

Re the last point, having quickly swapped the order on my local, as well as removing the `gsp_id`, I would be inclined to leave both as is for the moment: 
- maybe the first thing is just because I'm used to the order as is now, but similar to the Chart Headline figures (current + next forecast) and their labels, I don't think it makes much odds and to my brain the smaller data being the less important and less eye-drawing, if anything, actually makes more sense _further from the mouse_, and the main human readable name and Delta figure here are both larger and coloured, so as long as they stays in the same place, they will be easy to scan.
- on a different note, I think the `gsp_id` as it is doesn't detract in any way from the UX, which is my usual go-to rule for removing/changing elements, and even if we're not aware of any uses for data at present, we're providing a novel way to look at this data, so it may or may not be up to us how that ends up getting used! (I think that's all part of the fun with UI design, right?)
