### ISSUE TITLE
Display times in Europe/London not UTC

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#55]
Make sure all times are in the browser's time zone.

Note that all datetimes from API are in UTC

**Comment by peterdudfield** [comment]
@dctanner hope its ok, I add this to V2 milestone.

**Comment by peterdudfield** [comment]
Lets wait for feedback from NG ESO on this

**Comment by JackKelly** [comment]
IIRC, I'm 90% sure that ESO's systems display the time in local time (i.e. Europe/London). Although I agree we should wait for confirmation from ESO.

Although it might be a good idea to _always_ explicitly state which timezone we're displaying.

And, we'd need to decide what happens when our timeseries plot spans a daylight saving transition (e.g. half the plot is in UTC+0, and half is UTC+1). It's not instantly clear how to handle that, and how to make it super-clear which tick labels are UTC+0, and which are UTC+1.

**Comment by peterdudfield** [comment]
Hmm, yea, timezones are a nightmare. 

perhaps the simple step is to add some text below saying all timezones are UTC, and then we can think a bit about how to do it in Europre/London time

**Comment by JackKelly** [comment]
SGTM!

**Comment by peterdudfield** [comment]
see https://github.com/openclimatefix/nowcasting/issues/76

**Comment by peterdudfield** [comment]
Here's a way to change string with java script
```
date1.toLocaleString("en-GB", {timeZone: 'Europe/London'})
```
<img width="830" alt="Screenshot 2022-06-14 at 22 02 10" src="https://user-images.githubusercontent.com/34686298/173688481-4b1b27e4-9253-4373-9841-5ed66c742644.png">

**Comment by peterdudfield** [comment]
> Here's a way to change string with java script
> 
> ```
> date1.toLocaleString("en-GB", {timeZone: 'Europe/London'})
> ```
> 
> <img alt="Screenshot 2022-06-14 at 22 02 10" width="830" src="https://user-images.githubusercontent.com/34686298/173688481-4b1b27e4-9253-4373-9841-5ed66c742644.png">

Perhaps its not a simple as I thought
